### ISSUE TITLE
Ajustar filtro por relevância

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/thesaurus-wp-plugin#105]
Após análise foi identificado que o resultado por relevância não considera na ordenação dos resultados o critério de concordância exata
Exemplo:
Quando pesquisada a palavra China, o resultado apresenta o descritor *China* após *Terapia Alimentar Chinesa*  
![image](https://user-images.githubusercontent.com/93340661/202261108-16621028-ac2c-472e-95f3-af54e3e5fdf0.png)

O desejado seria que os descritores que contenham o termo exato pesquisado apareçam primeiro, antes dos demais.
Seria interessante entender qual o critério de ordenação foi utilizado no filtro de relevância.
Obrigada!
Luciana e @acecampos

**Comment by marcioalvessilva** [comment]
Após conversa com Wilson, foi informado que o método utilizado hoje é o mesmo usado no IAHX, será verificado quais as possibilidades para essa alteração.

**Comment by wilsonmoura** [comment]
@marcioalvessilva @lucianaPRB os parâmetros usados para definir a relevância dos resultados de pesquisa são definidos pelo próprio mecanismo que utilizamos para consultar o índice de pesquisa. Sendo assim, por limitações técnicas, não é possível ajustar esses parâmetros predefinidos.

**Comment by marcioalvessilva** [comment]
Grato pela explicação @wilsonmoura.
Considerando isso o que vocês sugerem @acecampos e @lucianaPRB , mantem por ordem alfabética ou por relevância usando o método IAHX?

**Comment by lucianaPRB** [comment]
@wilsonmoura Obrigada pelo retorno. Minha sugestão seria então de manter o resultado por relevância (embora entendamos que no futuro seria importante ser aperfeiçoado) como padrão, e deixar a apresentação alfabética como opção para o usuário.

**Comment by acecampos** [comment]
Bom dia, pessoal!

Obrigada, Wilson e Márcio.

Creio que será um ganho se deixar por relevância com o mesmo critério do IAhX e mantiver o botão com as opções "relevância" e "alfabético".

Abraços,

Ana Cristina Espindola Campos

Terminologias e Classificações em Saúde

BIREME<https://www.paho.org/bireme/index.php?lang=pt> | OPAS | OMS

 [cid:d2e6d08c-aa60-4106-9804-e1ecee67ed01]

________________________________
De: Márcio Alves ***@***.***>
Enviado: quinta-feira, 17 de novembro de 2022 07:26
Para: bireme/thesaurus-wp-plugin ***@***.***>
Cc: Campos, Ana Cristina Espindola (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/thesaurus-wp-plugin] Ajustar filtro por relevância (Issue #105)


Grato pela explicação @wilsonmoura<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwilsonmoura&data=05%7C01%7Ccamposan%40paho.org%7C1596fe870654479f955e08dac8863e49%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638042776147966128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dGSsItDIdV1GtOe9DzJ7A9KZIbttXT4K46GQflLgspo%3D&reserved=0>.
Considerando isso o que vocês sugerem @acecampos<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Facecampos&data=05%7C01%7Ccamposan%40paho.org%7C1596fe870654479f955e08dac8863e49%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638042776147966128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wr1mlCy%2FyvptH8mnqW9n9VRyyWQxd021CUt%2Fk%2FKbpe4%3D&reserved=0> e @lucianaPRB<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FlucianaPRB&data=05%7C01%7Ccamposan%40paho.org%7C1596fe870654479f955e08dac8863e49%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638042776147966128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YFWYDmIRTM6Z92e30GjGdFdaNTp7fOr02za8JSkEcKQ%3D&reserved=0> , mantem por ordem alfabética ou por relevância usando o método IAHX?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fthesaurus-wp-plugin%2Fissues%2F105%23issuecomment-1318417916&data=05%7C01%7Ccamposan%40paho.org%7C1596fe870654479f955e08dac8863e49%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638042776147966128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bGCbTVRlGhzmTPLJGyskSrEGtbL%2BTTSuFYzodLlaP0E%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINVH7XU6K73VBFTFSFYAWTWIYB6XANCNFSM6AAAAAASCQ5CU4&data=05%7C01%7Ccamposan%40paho.org%7C1596fe870654479f955e08dac8863e49%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638042776147966128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lPy4p2HDVRnHg%2FqmgdKNjA0q8B%2BkZoT2Hjv%2BY1k%2B5U4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Issue finalizado!
